// apps/www/src/routes/privacy.tsx
import { createPageComponent } from '@/components/PageApp'
import { createFileRoute } from '@/lib/page'
import { generateSEOHead, STATIC_PAGE_SEO } from '@/lib/seo'

export const Route = createFileRoute('/privacy')({
  component: PrivacyPage,
  head: () => generateSEOHead(STATIC_PAGE_SEO.privacy)
})

function PrivacyPage() {
  return (
    <div className='mx-auto max-w-2xl space-y-4 px-6 py-12'>
      <h1 className='text-3xl font-bold'>Privacy Policy</h1>
      <p className='text-muted-foreground'>
        Placeholder. Full policy coming soon. We store the minimum needed to run the service:
        account info, listening activity you create, and basic analytics. We do not sell your data.
      </p>
    </div>
  )
}

export const Page = createPageComponent(Route)

// apps/www/src/routes/(public)/privacy/+page.svelte
<script lang="ts">
  import PublicHead from '@/lib/components/public/PublicHead.svelte'
</script>

<PublicHead
  title="Privacy Policy"
  description="How goosebumps.fm handles account, listening and analytics data."
  canonical="/privacy"
/>
<article class="mx-auto max-w-2xl space-y-4 px-6 py-12">
  <h1 class="text-3xl font-black">Privacy Policy</h1>
  <p>
    We store the minimum information needed to run goosebumps.fm: account information, activity you
    choose to create, and basic service analytics.
  </p>
  <p>
    We do not sell your personal information. Authentication cookies are used to keep you signed in,
    and operational analytics help us keep the service reliable.
  </p>
  <p>Contact us if you want to ask about, correct, or remove your account information.</p>
</article>
