// apps/www/src/components/home/FeaturedMixHero.tsx
import { Link, useNavigate } from '@tanstack/react-router'
import { Disc3, Pause, Play, Radio } from 'lucide-react'
import { useState } from 'react'
import { DEFAULT_IMAGE_URL } from '@/lib/constants'
import { useFeaturedMix } from '@/lib/useFeaturedMix'
import {
  useAudioPlayerActions,
  useAudioPlayerPlaybackState
} from '@/store/audioPlayer'

function CreatorNames({
  creators
}: {
  creators?: { id: string; name: string; username: string | null }[]
}) {
  if (!creators || creators.length === 0) return null
  return (
    <p className='text-sm text-secondary-foreground'>
      {creators.map((c) => c.name).join(', ')}
    </p>
  )
}

export function FeaturedMixHero() {
  const { data: featuredMix, isPending } = useFeaturedMix()
  const { loadTrack, play, pause } = useAudioPlayerActions()
  const { audioSrc, isPlaying, currentTrackId } = useAudioPlayerPlaybackState()
  const navigate = useNavigate()
  const [error, setError] = useState<string | null>(null)

  const isThisMixLoaded =
    Boolean(audioSrc) && currentTrackId === featuredMix?.id

  const handlePlay = () => {
    if (!featuredMix) return
    setError(null)

    if (isThisMixLoaded) {
      isPlaying ? pause() : play()
      return
    }

    if (!featuredMix.url) {
      setError('No audio available for this mix')
      return
    }

    loadTrack(
      featuredMix.url,
      featuredMix.thumbnailUrl || '',
      featuredMix.title,
      featuredMix.id,
      featuredMix.creators,
      featuredMix.slug
    )
  }

  const showPause = isThisMixLoaded && isPlaying

  return (
    <div className='flex flex-col items-center w-full gap-6'>
      <div className='flex flex-col items-center w-full gap-4'>
        {featuredMix ? (
          <Link
            to='/mixes/$mixId'
            params={{ mixId: featuredMix.slug }}
            className='group'>
            <img
              src={featuredMix.thumbnailUrl || DEFAULT_IMAGE_URL}
              alt={featuredMix.title}
              className='object-cover w-36 h-36 transition-opacity rounded-sm md:w-48 md:h-48 lg:w-40 lg:h-40 group-hover:opacity-80'
            />
          </Link>
        ) : (
          <div className='w-36 h-36 rounded-sm md:w-48 md:h-48 lg:w-40 lg:h-40 bg-muted animate-pulse' />
        )}
        <div className='text-center'>
          <p className='text-xs tracking-wider uppercase text-muted-foreground/70'>
            Featured mix
          </p>
          {featuredMix ? (
            <>
              <Link
                to='/mixes/$mixId'
                params={{ mixId: featuredMix.slug }}
                className='text-lg font-semibold hover:underline'>
                {featuredMix.title}
              </Link>
              <CreatorNames creators={featuredMix.creators} />
            </>
          ) : (
            <>
              <div className='w-40 h-6 mx-auto rounded-sm bg-muted animate-pulse' />
              <div className='w-24 h-4 mx-auto mt-1 rounded-sm bg-muted animate-pulse' />
            </>
          )}
        </div>
      </div>

      <div className='flex flex-col items-stretch w-full gap-3'>
        <button
          type='button'
          onClick={handlePlay}
          disabled={isPending || !featuredMix}
          className='inline-flex items-center justify-center gap-3 px-6 py-4 text-base font-semibold transition-colors rounded-sm bg-highlight text-gb-bg hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50 disabled:cursor-not-allowed'>
          {isPending ? (
            <>
              <Disc3 className='w-5 h-5 animate-spin' />
              <span>Loading...</span>
            </>
          ) : showPause ? (
            <>
              <Pause className='w-5 h-5' />
              <span>Pause</span>
            </>
          ) : (
            <>
              <Play className='w-5 h-5' />
              <span>{isThisMixLoaded ? 'Resume' : 'Play featured mix'}</span>
            </>
          )}
        </button>

        <button
          type='button'
          onClick={() => navigate({ to: '/shows' })}
          className='inline-flex items-center justify-center gap-2 px-6 py-3 text-sm font-medium transition-colors border rounded-sm border-border text-secondary-foreground hover:text-foreground hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring'>
          <Radio className='w-4 h-4' />
          <span>Browse radio shows</span>
        </button>

        {error && <p className='text-sm text-center text-red-500'>{error}</p>}
      </div>
    </div>
  )
}

// apps/www/src/lib/components/public/FeaturedMixHero.svelte
<script lang="ts">
  import Artwork from './Artwork.svelte'
  import { getPlayerContext } from '@/lib/player/context'
  import { records, text, type PublicRecord } from '@/lib/public-content'

  let { mix }: { mix: PublicRecord | undefined } = $props()

  const player = getPlayerContext()

  let error = $state('')

  const title = $derived(text(mix?.title, 'Featured mix'))

  const creators = $derived(records(mix?.creators).map((creator) => text(creator.name)).filter(Boolean).join(', '))

  const play = () => {
    const url = text(mix?.url)

    if (!url) { error = 'No audio available for this mix';

 return }

    error = ''
    player.play({
      id: text(mix?.id, url), slug: text(mix?.slug), type: 'mix', url, title,
      thumbnailUrl: text(mix?.thumbnailUrl) || null
    })
  }
</script>

<div class="flex w-full flex-col gap-3">
  <div class="relative aspect-square w-full overflow-hidden border-2 border-foreground bg-muted">
    {#if mix}<Artwork {...(text(mix.thumbnailUrl) ? { src: text(mix.thumbnailUrl) } : {})} alt={title} />{:else}<div class="h-full animate-pulse bg-muted"></div>{/if}
    <div class="absolute inset-0 bg-gradient-to-t from-black/90 via-black/35 to-transparent"></div>
    <div class="absolute inset-0 flex flex-col justify-between p-3">
      <span class="self-start bg-highlight px-2 py-1 text-[10px] font-bold uppercase tracking-[.25em] text-highlight-foreground">Featured</span>
      <div class="flex flex-col gap-3">
        <div>{#if mix}<a href={`/mixes/${text(mix.slug, text(mix.id))}`} class="text-2xl font-black leading-none text-white decoration-highlight hover:underline">{title}</a>{#if creators}<p class="mt-1 text-xs font-bold tracking-widest text-white/70">{creators}</p>{/if}{:else}<p class="font-bold text-white/70">No featured mix available</p>{/if}</div>
        <button disabled={!mix} onclick={play} class="w-full bg-highlight px-5 py-3 font-bold tracking-widest text-highlight-foreground disabled:opacity-50">▶ Play mix</button>
      </div>
    </div>
  </div>
  <a href="/shows" class="border-2 border-foreground px-5 py-3 text-center text-xs font-bold tracking-widest no-underline hover:bg-foreground hover:text-background">◉ Browse radio shows</a>
  {#if error}<p role="alert" class="text-xs font-bold text-destructive">{error}</p>{/if}
</div>
