// apps/www/src/components/shows/ShowsBrowser.tsx
import { ShowsSkeleton } from '@gbfm/ui'
import { LoadMoreTrigger } from '@/components/LoadMoreTrigger'
import { useAllShows } from '@/lib/http'
import { EpisodeGrid } from './EpisodeGrid'
import { ShowListItem } from './ShowListItem'
import { ShowMetaBlock, type ShowMeta } from './ShowMetaBlock'
import { ShowSwitcherRail } from './ShowSwitcherRail'

interface ShowsBrowserProps {
  selectedShow: ShowMeta | undefined
  onSelectShow: (slug: string) => void
}

export function ShowsBrowser({ selectedShow, onSelectShow }: ShowsBrowserProps) {
  const { data, isPending, error, fetchNextPage, hasNextPage, isFetchingNextPage } = useAllShows({
    limit: 50
  })

  if (isPending && !selectedShow) {
    return <ShowsSkeleton />
  }

  if (error && !selectedShow) {
    return (
      <div className='p-4 text-center text-destructive'>Error loading shows: {error.message}</div>
    )
  }

  if (!isPending && data.length === 0 && !selectedShow) {
    return <div className='p-4 text-center text-muted-foreground'>No shows found</div>
  }

  return (
    <div className='grid grid-cols-1 gap-6 lg:grid-cols-[220px_minmax(0,1fr)_240px] lg:gap-10'>
      <aside className='hidden lg:block'>
        <div className='no-scrollbar sticky top-4 max-h-[calc(100dvh-8rem)] overflow-y-auto'>
          {selectedShow && (
            <>
              <h2 className='mb-2 border-b border-border/60 pb-2 text-xs font-semibold tracking-wider text-muted-foreground'>
                Show
              </h2>
              <ShowMetaBlock show={selectedShow} />
            </>
          )}
        </div>
      </aside>

      <div className='space-y-4 lg:hidden'>
        <ShowSwitcherRail
          shows={data}
          selectedShowId={selectedShow?.id}
          onSelect={(show) => onSelectShow(show.slug)}
        />
        {selectedShow && <ShowMetaBlock show={selectedShow} />}
        <LoadMoreTrigger
          onLoadMore={fetchNextPage}
          hasNextPage={hasNextPage}
          isFetchingNextPage={isFetchingNextPage}
        />
      </div>

      <main className='min-w-0'>
        {selectedShow && (
          <h1 className='mb-3 border-b border-border/60 pb-2 text-xs font-semibold tracking-wider text-muted-foreground'>
            Episodes
          </h1>
        )}
        {selectedShow ? (
          <EpisodeGrid showSlug={selectedShow.slug} />
        ) : (
          <div className='py-12 text-center text-muted-foreground'>
            Select a show to browse its mixes
          </div>
        )}
      </main>

      <aside className='hidden lg:block'>
        <div className='no-scrollbar sticky top-4 max-h-[calc(100dvh-8rem)] overflow-y-auto pl-1'>
          <h2 className='mb-2 border-b border-border/60 pb-2 text-xs font-semibold tracking-wider text-muted-foreground'>
            All shows
          </h2>
          <nav aria-label='Shows' className='font-mono text-base'>
            {data.map((show) => (
              <ShowListItem
                key={show.id}
                show={show}
                isSelected={selectedShow?.id === show.id}
                onSelect={() => onSelectShow(show.slug)}
              />
            ))}
            <LoadMoreTrigger
              onLoadMore={fetchNextPage}
              hasNextPage={hasNextPage}
              isFetchingNextPage={isFetchingNextPage}
            />
          </nav>
        </div>
      </aside>
    </div>
  )
}

// apps/www/src/lib/components/public/ShowsBrowser.svelte
<script lang="ts">
  import EpisodeList from './EpisodeList.svelte'
  import PublicHead from './PublicHead.svelte'
  import PublicState from './PublicState.svelte'
  import ShowListItem from './ShowListItem.svelte'
  import ShowMeta from './ShowMeta.svelte'
  import ShowSwitcherRail from './ShowSwitcherRail.svelte'
  import { text, type PublicRecord } from '@/lib/public-content'

  let { shows, selected, episodes = [], failure = null, actionActive = false }: { shows: ReadonlyArray<PublicRecord>; selected: PublicRecord | null; episodes?: ReadonlyArray<PublicRecord>; failure?: string | null; actionActive?: boolean } = $props()

  const selectedId = $derived(text(selected?.id))

  const heading = 'mb-2 border-b border-border/60 pb-2 text-xs font-semibold tracking-wider text-muted-foreground'
</script>

<PublicHead title={selected ? text(selected.title, 'Radio Shows') : 'Radio Shows'} description={selected ? text(selected.description, 'Listen to radio shows on goosebumps.fm.') : 'Regular radio shows, hosts and episodes on goosebumps.fm.'} canonical={selected ? `/shows/${text(selected.slug)}` : '/shows'} {...(selected && text(selected.thumbnailUrl) ? { image: text(selected.thumbnailUrl) } : {})} />
{#if failure}
  <PublicState message={failure} error />
{:else if shows.length === 0 && !selected}
  <PublicState message="No shows found" />
{:else}
  <div class="grid w-full grid-cols-1 gap-6 px-4 py-4 sm:px-6 sm:py-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
    <aside class="hidden lg:block">
      <div class="no-scrollbar sticky top-4 max-h-[calc(100dvh-8rem)] overflow-y-auto">
        <h2 class={heading}>Radio shows</h2>
        <nav aria-label="Shows" class="font-mono text-base">
          {#each shows as show (text(show.id))}
            <ShowListItem {show} selected={text(show.id) === selectedId} />
          {/each}
        </nav>
      </div>
    </aside>

    <div class="lg:hidden"><ShowSwitcherRail {shows} {selectedId} /></div>

    <main class="min-w-0 max-w-4xl space-y-8">
      {#if selected}
        <ShowMeta show={selected} {actionActive} />
        <section>
          <h2 class={heading}>Episodes</h2>
          <EpisodeList {episodes} />
        </section>
      {:else}
        <PublicState message="Select a show to browse its mixes" />
      {/if}
    </main>
  </div>
{/if}
