// apps/www/src/routes/spotify/callback.tsx
import { createPageComponent } from '@/components/PageApp'
import { createFileRoute } from '@/lib/page'
import { useNavigate } from '@/lib/navigation'
import * as Effect from 'effect/Effect'
import { useEffect, useState } from 'react'
import {
  clearAuthorizationCallback,
  exchangeSpotifyPkceCodeEffect,
  notifySpotifySessionChanged,
  readAuthorizationCallback,
  type SpotifyRequestError,
  spotifyErrorMessage,
  takeSpotifyReturnPath
} from '@/lib/spotify-pkce'
import { runAppEffect } from '@/runtime'
import { privateHead } from '@/lib/seo'

export const Route = createFileRoute('/spotify/callback')({
  component: SpotifyCallback,
  head: () => privateHead('Spotify connection')
})

function SpotifyCallback() {
  const navigate = useNavigate()
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const url = new URL(window.location.href)
    const callback = readAuthorizationCallback(url)
    const returnPath = takeSpotifyReturnPath()

    if (callback.error) {
      clearAuthorizationCallback(url)
      setError(callback.error)
      return
    }

    if (!callback.code) {
      setError('Missing authorization code.')
      return
    }

    void runAppEffect(
      exchangeSpotifyPkceCodeEffect(callback.code).pipe(
        Effect.map(() => {
          notifySpotifySessionChanged()
          void navigate({ to: returnPath, replace: true })
        }),
        Effect.catch((e: SpotifyRequestError) =>
          Effect.sync(() => setError(spotifyErrorMessage(e)))
        )
      )
    )
  }, [navigate])

  return (
    <div className='flex min-h-[50vh] flex-col items-center justify-center gap-3 px-6 text-center'>
      {error ? (
        <>
          <h1 className='text-base font-bold tracking-widest text-destructive'>
            Spotify connection failed
          </h1>
          <p className='max-w-md text-xs font-medium tracking-wider text-muted-foreground'>
            {error}
          </p>
          <button
            type='button'
            onClick={() => void navigate({ to: '/dashboard/player', replace: true })}
            className='mt-2 text-xs font-bold tracking-widest underline underline-offset-4'>
            Back to Player Settings
          </button>
        </>
      ) : (
        <p className='text-base font-medium tracking-wider text-muted-foreground'>
          Connecting Spotify…
        </p>
      )}
    </div>
  )
}

export const Page = createPageComponent(Route)

// apps/www/src/routes/(account)/spotify/callback/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import * as Effect from 'effect/Effect'
  import {
    clearAuthorizationCallback,
    exchangeSpotifyPkceCodeEffect,
    notifySpotifySessionChanged,
    readAuthorizationCallback,
    spotifyErrorMessage,
    takeSpotifyReturnPath,
    type SpotifyRequestError,
  } from '@/lib/spotify-pkce'
  import { runAppEffect } from '@/runtime'

  let error = $state('')

  $effect(() => {
    void (async () => {
      const url = new URL(page.url.href)
      const callback = readAuthorizationCallback(url)
      const destination = takeSpotifyReturnPath()

      if (callback.error) {
        clearAuthorizationCallback(url)
        error = callback.error

        return
      }

      if (!callback.code) {
        error = 'Missing authorization code.'

        return
      }

      await runAppEffect(
        exchangeSpotifyPkceCodeEffect(callback.code).pipe(
          Effect.tap(() => Effect.sync(notifySpotifySessionChanged)),
          Effect.catch((cause: SpotifyRequestError) =>
            Effect.sync(() => {
              error = spotifyErrorMessage(cause)
            }),
          ),
        ),
      )

      if (!error) await goto(destination, { replaceState: true })
    })()
  })
</script>

<svelte:head><title>Spotify connection</title></svelte:head>
<section class="mx-auto max-w-xl px-4 py-20 text-center">
  {#if error}<h1 class="text-2xl font-black text-destructive">Spotify connection failed</h1>
    <p class="mt-4">{error}</p>
    <a class="mt-6 inline-block" href="/dashboard/player">Back to Player Settings</a>{:else}<p>
      Connecting Spotify…
    </p>{/if}
</section>
