// apps/www/src/routes/auth/reset-password.tsx
import { getFormString } from '@gbfm/core/utils'
import { GenericAuthForm, isPasswordValid, PasswordChecklist } from '@gbfm/ui'
import { useMutation } from '@tanstack/react-query'
import { Schema } from 'effect'
import { useState } from 'react'
import { AuthPageLayout, AuthStatusNotice } from '@/components/Auth/AuthPageLayout'
import { createPageComponent } from '@/components/PageApp'
import { useSession } from '@/lib/auth-client'
import { apiUrl } from '@/lib/http'
import { Link, useNavigate } from '@/lib/navigation'
import { createFileRoute } from '@/lib/page'
import { readResponseErrorMessage } from '@/lib/response'
import { privateHead } from '@/lib/seo'

export const searchSchema = Schema.Struct({
  token: Schema.optional(Schema.String),
  error: Schema.optional(Schema.String)
})

export const Route = createFileRoute('/auth/reset-password')({
  component: ResetPasswordRoutePage,
  head: () => privateHead('Reset password'),
  validateSearch: Schema.toStandardSchemaV1(searchSchema)
})

export const Page = createPageComponent(Route)

async function confirmInvite(token: string, password: string) {
  const res = await fetch(apiUrl('/invite/confirm'), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    credentials: 'include',
    body: JSON.stringify({ token, password })
  })
  if (!res.ok) {
    throw new Error(await readResponseErrorMessage(res, 'Failed to reset password'))
  }
}

function ResetPasswordRoutePage() {
  return <ResetPasswordPage search={Route.useSearch()} />
}

function ResetPasswordPage({ search }: { search: typeof searchSchema.Type }) {
  const navigate = useNavigate()
  const { data: session, refetch: refetchSession } = useSession()
  const [password, setPassword] = useState('')
  const [mismatchError, setMismatchError] = useState(false)
  const existingSessionEmail = session?.user?.email

  const isValidToken = !search.error && Boolean(search.token)

  const { mutate, isPending, isSuccess, error } = useMutation({
    mutationFn: ({ password }: { password: string }) => {
      if (!search.token) {
        throw new Error('Missing reset token')
      }

      return confirmInvite(search.token, password)
    },
    onSuccess: async () => {
      await refetchSession()
      void navigate({ to: '/' })
    }
  })

  const onSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    const password = getFormString(formData, 'password')
    const confirmPassword = getFormString(formData, 'confirmPassword')

    if (!isPasswordValid(password)) return
    if (password !== confirmPassword) {
      setMismatchError(true)
      return
    }
    if (!search.token) return

    setMismatchError(false)
    mutate({ password })
  }

  if (!isValidToken) {
    return (
      <AuthPageLayout
        badge='Reset Link'
        title='That reset link is no longer valid'
        description='Request a fresh password reset email and we will help you back in.'
        status={
          search.error ? (
            <AuthStatusNotice variant='error'>
              Invalid or expired reset link. Please request a new password reset.
            </AuthStatusNotice>
          ) : null
        }
        footer={
          <div className='space-y-3 border-t border-gb-pastel-green-2/20 pt-4 text-base text-muted-foreground'>
            <p>
              Need a new link?{' '}
              <Link
                to='/auth/forgot-password'
                className='font-medium text-gb-pastel-green-1 underline-offset-4 hover:text-gb-highlight'>
                Request another reset email
              </Link>
            </p>
          </div>
        }>
        <div className='border border-gb-pastel-green-2/20 bg-background/50 px-4 py-4 text-base leading-6 text-muted-foreground'>
          Reset links expire for safety. If the email is still in your inbox, the newest link is the
          one to use.
        </div>
      </AuthPageLayout>
    )
  }

  return (
    <AuthPageLayout
      badge='Reset Password'
      title='Choose a new password'
      description='Set a fresh password for your account and we will log you straight in.'
      status={
        isSuccess ? (
          <AuthStatusNotice variant='success'>Password set! Taking you in...</AuthStatusNotice>
        ) : mismatchError ? (
          <AuthStatusNotice variant='error'>Passwords do not match.</AuthStatusNotice>
        ) : error ? (
          <AuthStatusNotice variant='error'>{error.message}</AuthStatusNotice>
        ) : existingSessionEmail ? (
          <AuthStatusNotice variant='warning'>
            You're currently signed in as {existingSessionEmail}. Setting a new password here will
            sign you out of that account and into this one.
          </AuthStatusNotice>
        ) : null
      }
      footer={
        <div className='space-y-3 border-t border-gb-pastel-green-2/20 pt-4 text-base text-muted-foreground'>
          <p>
            Remembered it after all?{' '}
            <Link
              to='/auth/sign-in'
              className='font-medium text-gb-pastel-green-1 underline-offset-4 hover:text-gb-highlight'>
              Sign in instead
            </Link>
          </p>
        </div>
      }>
      <GenericAuthForm
        formTitle='Reset Password'
        fields={[
          {
            name: 'password',
            label: 'New Password',
            type: 'password',
            placeholder: 'Enter new password',
            required: true,
            autoComplete: 'new-password',
            autoFocus: true,
            onChange: (value) => {
              setPassword(value)
              setMismatchError(false)
            },
            belowField: <PasswordChecklist password={password} />
          },
          {
            name: 'confirmPassword',
            label: 'Confirm Password',
            type: 'password',
            placeholder: 'Confirm new password',
            required: true,
            autoComplete: 'new-password',
            onChange: () => setMismatchError(false)
          }
        ]}
        onSubmit={onSubmit}
        submitButtonText='Reset Password'
        isSubmitting={isPending}
        submitDisabled={!isPasswordValid(password)}
      />
    </AuthPageLayout>
  )
}

// apps/www/src/routes/(account)/auth/reset-password/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import type { PageProps } from './$types'

  let { data }: PageProps = $props()
  const token = page.url.searchParams.get('token')
  const linkError = page.url.searchParams.get('error')
  let password = $state('')
  let confirmation = $state('')
  let pending = $state(false)
  let error = $state('')
  const checks = $derived([
    ['At least 8 characters', password.length >= 8],
    ['An uppercase and lowercase letter', /[a-z]/.test(password) && /[A-Z]/.test(password)],
    ['A number', /\d/.test(password)]
  ] as const)
  const valid = $derived(checks.every(([, passed]) => passed))

  async function submit() {
    error = ''
    if (!valid) return
    if (password !== confirmation) { error = 'Passwords do not match.'; return }
    if (!token) return
    pending = true
    try {
      const response = await fetch('/api/invite/confirm', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, password }) })
      if (!response.ok) throw new Error('Failed to reset password. The link may have expired.')
      await goto('/', { invalidateAll: true })
    } catch (cause) { error = cause instanceof Error ? cause.message : 'Failed to reset password.' }
    finally { pending = false }
  }
</script>

<svelte:head><title>Reset password</title></svelte:head>
{#if !token || linkError}
  <section class="mx-auto max-w-xl px-4 py-20">
    <p class="text-xs font-bold uppercase tracking-[.25em] text-highlight">Reset link</p>
    <h1 class="mt-2 text-4xl font-black">That reset link is no longer valid</h1>
    {#if linkError}<p role="alert" class="mt-5 border border-destructive p-3 text-destructive">Invalid or expired reset link. Please request a new password reset.</p>{/if}
    <p class="mt-5 text-muted-foreground">Reset links expire for safety. The newest link in your inbox is the one to use.</p>
    <a class="mt-6 inline-block font-semibold underline" href="/auth/forgot-password">Request another reset email</a>
  </section>
{:else}
  <section class="mx-auto max-w-xl px-4 py-16">
    <p class="text-xs font-bold uppercase tracking-[.25em] text-highlight">Reset password</p>
    <h1 class="mt-2 text-4xl font-black">Choose a new password</h1>
    <p class="mt-3 text-muted-foreground">Set a fresh password and we will log you straight in.</p>
    {#if data.principal._tag === 'Authenticated'}<p class="mt-6 border border-amber-500/50 bg-amber-500/10 p-3" role="status">You’re currently signed in as {data.principal.email}. Setting a password here will switch to the account from the reset link.</p>{/if}
    {#if error}<p class="mt-4 border border-destructive p-3 text-destructive" role="alert">{error}</p>{/if}
    <form class="mt-8 grid gap-5" onsubmit={(event) => { event.preventDefault(); void submit() }}>
      <label class="grid gap-2 font-semibold">New password<input class="border bg-background px-3 py-2" bind:value={password} type="password" autocomplete="new-password" required /></label>
      <ul class="grid gap-1 text-xs">{#each checks as [label, passed]}<li class={passed ? 'text-highlight' : 'text-muted-foreground'}>{passed ? '✓' : '○'} {label}</li>{/each}</ul>
      <label class="grid gap-2 font-semibold">Confirm password<input class="border bg-background px-3 py-2" bind:value={confirmation} type="password" autocomplete="new-password" required /></label>
      <button class="bg-primary px-4 py-3 font-bold text-primary-foreground disabled:opacity-50" disabled={pending || !valid}>{pending ? 'Resetting…' : 'Reset password'}</button>
    </form>
    <a class="mt-6 inline-block text-sm underline" href="/auth/sign-in">Sign in instead</a>
  </section>
{/if}
