// apps/www/src/routes/(dashboard)/dashboard/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types'
  import FavoritesSection from '@/lib/components/dashboard/FavoritesSection.svelte'
  import Page from '@/lib/components/dashboard/Page.svelte'
  import RemindersCard from '@/lib/components/dashboard/RemindersCard.svelte'
  let { data }: PageProps = $props()
</script>
<Page title={`Welcome back, ${data.principal._tag === 'Authenticated' ? data.principal.name.split(' ')[0] : 'there'}`} description="Here's what's happening">
  <div class="grid grid-cols-1 gap-8 sm:gap-12 lg:grid-cols-12"><div class="lg:col-span-8"><FavoritesSection /></div><div class="lg:col-span-4"><RemindersCard /></div></div>
</Page>

// apps/www/src/routes/dashboard/index.tsx
import { createPageComponent } from '@/components/PageApp'
import { createFileRoute } from '@/lib/page'
import { DashboardLayout } from '@/components/dashboard/DashboardLayout'
import { FavoritesSection } from '@/components/dashboard/FavoritesSection'
import { RemindersCard } from '@/components/dashboard/RemindersCard'
import { useSession } from '@/lib/auth-client'

export const Route = createFileRoute('/dashboard/')({
  component: DashboardHome
})

export const Page = createPageComponent(Route)

function DashboardHome() {
  const { data: session } = useSession()
  const firstName = session?.user.name.split(' ')[0] || 'there'

  return (
    <DashboardLayout title={`Welcome back, ${firstName}`} description="Here's what's happening">
      <div className='grid grid-cols-1 gap-8 sm:gap-12 lg:grid-cols-12'>
        <div className='lg:col-span-8'>
          <FavoritesSection />
        </div>
        <div className='lg:col-span-4'>
          <RemindersCard />
        </div>
      </div>
    </DashboardLayout>
  )
}
