// apps/www/src/routes/(dashboard)/dashboard/integrations/+page.svelte
<script lang="ts">
  import Page from '@/lib/components/dashboard/Page.svelte'
  import SpotifyConnection from '@/lib/components/dashboard/settings/SpotifyConnection.svelte'
</script>

<Page title="Integrations" description="Connect the services Goosebumps uses for music."><SpotifyConnection /></Page>

// apps/www/src/routes/dashboard/integrations.tsx
import { createPageComponent } from '@/components/PageApp'
import { createFileRoute } from '@/lib/page'
import { DashboardLayout } from '@/components/dashboard/DashboardLayout'
import { SpotifyConnectionCard } from '@/components/spotify/SpotifyConnectionCard'

export const Route = createFileRoute('/dashboard/integrations')({
  component: DashboardIntegrations
})

export const Page = createPageComponent(Route)

function DashboardIntegrations() {
  return (
    <DashboardLayout
      title='Integrations'
      description='Connect the services Goosebumps uses for music.'>
      <div className='space-y-12'>
        <SpotifyConnectionCard />
      </div>
    </DashboardLayout>
  )
}
