// apps/www/src/routes/(dashboard)/dashboard/profile/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types'
  import Page from '@/lib/components/dashboard/Page.svelte'
  import ProfileSettings from '@/lib/components/dashboard/settings/ProfileSettings.svelte'
  let { data }: PageProps = $props()
</script>

<Page title="Account Profile" description="Manage your account details and password."><ProfileSettings initialProfile={data.profile} initialError={data.failure} /></Page>

// apps/www/src/routes/dashboard/profile.tsx
import { createPageComponent } from '@/components/PageApp'
import { createFileRoute } from '@/lib/page'
import { ChangePasswordCard } from '@/components/dashboard/ChangePasswordCard'
import { DashboardLayout } from '@/components/dashboard/DashboardLayout'
import { ProfileCard } from '@/components/dashboard/ProfileCard'
import { SocialLinksCard } from '@/components/dashboard/SocialLinksCard'
import { useSession } from '@/lib/auth-client'

export const Route = createFileRoute('/dashboard/profile')({
  component: DashboardProfile
})

export const Page = createPageComponent(Route)

function DashboardProfile() {
  const { data: session } = useSession()

  return (
    <DashboardLayout
      title='Account Profile'
      description='Manage your account details and password.'>
      {session?.user ? (
        <div className='space-y-6'>
          <ProfileCard user={session.user} />
          <SocialLinksCard />
          <ChangePasswordCard email={session.user.email} />
        </div>
      ) : null}
    </DashboardLayout>
  )
}
