// apps/www/src/routes/+page.svelte
<svelte:head>
  <title>goosebumps.fm — online community radio</title>
  <meta
    name="description"
    content="Independent radio, mixes, music writing and community from Johannesburg." />
  <link rel="canonical" href="https://goosebumps.fm/" />
</svelte:head>

<div class="flex min-h-full items-center justify-center px-6 py-8 lg:py-0">
  <h1
    class="my-0 w-fit text-right font-bold leading-[0.85] tracking-tight text-[min(12vw,4.5rem)] md:text-8xl lg:text-7xl xl:text-9xl">
    goosebumps.<br />
    <span class="text-highlight">fm</span>
  </h1>
</div>

// web/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
	component: Index,
});

function Index() {
	return (
		<div className="flex flex-col justify-center items-center px-1 leading-none h-dvh">
			<h1 className="my-0 text-5xl font-bold text-right w-fit md:text-8xl xl:text-9xl">
				goosebumps.
				<br />
				<span className="text-highlight">fm</span>
			</h1>
		</div>
	);
}
