// apps/www/src/routes/auth/forgot-password.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { GenericAuthForm } from '@/components/Auth/GenericForm'
import { authClient } from '@/lib/auth-client'

export const Route = createFileRoute('/auth/forgot-password')({
  component: ForgotPasswordPage
})

function ForgotPasswordPage() {
  const [message, setMessage] = useState<string>('')
  const [error, setError] = useState<string>('')

  const onSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    const email = formData.get('email') as string

    try {
      const result = await authClient.requestPasswordReset({
        email,
        redirectTo: `${window.location.origin}/auth/reset-password`
      })

      if (result.error) {
        setError(result.error.message || 'Failed to send reset email')
        setMessage('')
      } else {
        setMessage('Password reset email sent! Check your inbox.')
        setError('')
      }
    } catch (_err) {
      setError('Failed to send reset email')
      setMessage('')
    }
  }

  return (
    <div className=''>
      <div className='w-full max-w-md mx-auto space-y-8'>
        {message && (
          <div className='p-4 text-sm text-green-700 bg-green-100 rounded-md'>
            {message}
          </div>
        )}

        {error && (
          <div className='p-4 text-sm text-red-700 bg-red-100 rounded-md'>
            {error}
          </div>
        )}

        <GenericAuthForm
          formTitle='I Forgot My Password'
          fields={[
            {
              name: 'email',
              label: 'Email',
              type: 'email',
              placeholder: 'name@example.com',
              required: true
            }
          ]}
          onSubmit={onSubmit}
          submitButtonText='Send Reset Email'
        />
      </div>
    </div>
  )
}

// apps/www/src/routes/(account)/auth/forgot-password/+page.svelte
<script lang="ts">
  import AccountForm from '@/lib/components/account/AccountForm.svelte'

  let sent = $state('')
</script>
<svelte:head><title>Forgot password</title></svelte:head>
{#if sent}<section class="mx-auto max-w-xl px-4 py-20"><h1 class="text-4xl font-black">Check your inbox.</h1><p class="mt-4">We sent a reset link to {sent}.</p></section>{:else}<AccountForm title="Reset your password" description="Enter the email tied to your account." submitLabel="Send reset email" endpoint="/auth/request-password-reset" fields={[{name:'email',label:'Email',type:'email'}]} transform={(v) => ({email:v.email, redirectTo:`${location.origin}/auth/reset-password`})} onSuccess={(values) => sent=values.email} />{/if}
