// apps/www/src/components/dashboard/FavoritesSection.tsx
import { Link } from '@tanstack/react-router'
import { Heart } from 'lucide-react'
import { DEFAULT_IMAGE_URL } from '@/lib/constants'
import type { Favorite } from '@/lib/http'
import { useFavorites } from '@/lib/http'
import { PlayPauseButton } from '../PlayPauseButton'

type AudioFavorite = Favorite & { audio: NonNullable<Favorite['audio']> }

export function FavoritesSection() {
  const { data: favorites, isPending } = useFavorites()

  if (isPending) {
    return (
      <div>
        <h3 className='flex items-center gap-2 text-sm font-medium text-muted-foreground mb-3'>
          <Heart className='w-4 h-4' />
          Favorites
        </h3>
        <p className='text-sm text-muted-foreground'>Loading...</p>
      </div>
    )
  }

  const audioFavorites = favorites.filter((f): f is AudioFavorite => f.audio !== null)

  if (audioFavorites.length === 0) {
    return null
  }

  return (
    <div className='flex flex-col h-full rounded-sm overflow-hidden'>
      <h3 className='flex items-center gap-2 text-xs font-bold text-foreground uppercase tracking-widest mb-6'>
        <Heart className='w-3.5 h-3.5 text-red-500' />
        Favorites
      </h3>
      <div className='space-y-3'>
        {audioFavorites.slice(0, 6).map((favorite) => (
          <div
            key={favorite.id}
            className='flex items-center gap-4 p-2 rounded-sm hover:bg-muted/40 transition-all duration-300 group'>
            <div className='relative shrink-0'>
              <img
                src={favorite.audio.thumbnailUrl || DEFAULT_IMAGE_URL}
                alt={favorite.audio.title}
                className='w-12 h-12 rounded-sm object-cover border border-border/50'
              />
              <div className='absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity'>
                <PlayPauseButton
                  url={favorite.audio.url}
                  thumbnailUrl={favorite.audio.thumbnailUrl || ''}
                  title={favorite.audio.title}
                  trackId={favorite.audio.id}
                />
              </div>
            </div>
            <div className='flex-1 min-w-0'>
              {favorite.audio.type === 'mix' ? (
                <Link
                  to='/mixes/$mixId'
                  params={{ mixId: favorite.audio.slug }}
                  className='text-sm font-bold uppercase tracking-tight truncate block no-underline hover:text-primary transition-colors'>
                  {favorite.audio.title}
                </Link>
              ) : favorite.audio.type === 'track' ? (
                <Link
                  to='/tracks/$trackId'
                  params={{ trackId: favorite.audio.slug }}
                  className='text-sm font-bold uppercase tracking-tight truncate block no-underline hover:text-primary transition-colors'>
                  {favorite.audio.title}
                </Link>
              ) : (
                <span className='text-sm font-bold uppercase tracking-tight truncate block'>
                  {favorite.audio.title}
                </span>
              )}
              <p className='text-[9px] font-bold uppercase tracking-widest text-muted-foreground mt-1'>
                {favorite.audio.type}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// apps/www/src/lib/components/dashboard/FavoritesSection.svelte
<script lang="ts">
  import { GetFavoritesResponse } from '@gbfm/api/favorites'
  import { Heart, Play } from 'lucide-svelte'
  import { DEFAULT_IMAGE_URL } from '@/lib/constants'

  let { favorites, error = null }: { favorites: typeof GetFavoritesResponse.Type.favorites; error?: string | null } = $props()

  const audioFavorites = $derived(favorites.filter((favorite) => favorite.audio !== null).slice(0, 6))
</script>

<section aria-labelledby="favorites-heading">
  <h2 id="favorites-heading" class="mb-6 flex items-center gap-2 text-xs font-bold tracking-widest">
    <Heart class="size-3.5 text-red-500" /> Favorites
  </h2>
  {#if error}
    <p class="rounded border border-destructive/50 p-4 text-sm text-destructive">{error}</p>
  {:else if audioFavorites.length === 0}
    <div class="rounded border border-dashed p-8 text-center"><Heart class="mx-auto mb-3 size-6 text-muted-foreground" /><p class="font-semibold">No favorites yet</p><a class="mt-2 inline-block text-sm underline" href="/mixes">Discover mixes</a></div>
  {:else}
    <div class="space-y-3">
      {#each audioFavorites as favorite}
        {@const audio = favorite.audio}
        {#if audio}
          <a class="group flex items-center gap-4 rounded p-2 no-underline transition-colors hover:bg-muted/40" href={audio.type === 'mix' ? `/mixes/${audio.slug}` : audio.type === 'track' ? `/tracks/${audio.slug}` : audio.url}>
            <span class="relative shrink-0"><img class="size-12 rounded border object-cover" src={audio.thumbnailUrl || DEFAULT_IMAGE_URL} alt="" /><span class="absolute inset-0 grid place-items-center bg-black/45 opacity-0 transition-opacity group-hover:opacity-100"><Play class="size-5 fill-white text-white" /></span></span>
            <span class="min-w-0"><strong class="block truncate">{audio.title}</strong><small class="mt-1 block font-bold uppercase tracking-widest text-muted-foreground">{audio.type}</small></span>
          </a>
        {/if}
      {/each}
    </div>
  {/if}
</section>
