// apps/www/src/components/dashboard/RemindersCard.tsx
import { Link } from '@/lib/navigation'
import { Bell, Plus } from 'lucide-react'
import { useMusicReminders } from '@/lib/http'

const UPCOMING_LIMIT = 5
const RECENT_LIMIT = 4

interface MusicReminder {
  id: string
  musicTitle: string
  artistName: string
  albumCoverUrl: string | null
  reminderDate: string
  isSent: boolean
}

export function RemindersCard() {
  const { data, isPending } = useMusicReminders()

  const upcomingReminders =
    data?.reminders
      .filter((r) => !r.isSent)
      .toSorted(
        (a, b) => new Date(a.reminderDate).getTime() - new Date(b.reminderDate).getTime()
      ) ?? []

  const historyReminders =
    data?.reminders
      .filter((r) => r.isSent)
      .toSorted(
        (a, b) => new Date(b.reminderDate).getTime() - new Date(a.reminderDate).getTime()
      ) ?? []

  const isEmpty = !isPending && upcomingReminders.length === 0 && historyReminders.length === 0

  return (
    <div className='flex flex-col h-full bg-card/15 rounded-sm overflow-hidden'>
      <div className='flex items-center justify-between p-5 bg-muted/10'>
        <h3 className='flex items-center gap-2 text-xs font-bold text-foreground tracking-widest'>
          <Bell className='w-3.5 h-3.5 text-primary' />
          Reminders
        </h3>
        <div className='flex items-center gap-3'>
          <Link
            to='/reminders'
            className='flex items-center gap-1 text-[10px] font-bold tracking-widest text-primary no-underline hover:text-primary/80 transition-colors'>
            <Plus className='w-3 h-3' />
            New
          </Link>
          <div className='w-px h-3 bg-border/50' />
          <Link
            to='/reminders'
            className='text-[10px] font-bold tracking-widest text-muted-foreground no-underline hover:text-primary transition-colors'>
            Manage
          </Link>
        </div>
      </div>

      <div className='flex-1 p-5'>
        {isPending ? (
          <div className='flex flex-col gap-4'>
            {[1, 2, 3].map((i) => (
              <div key={i} className='h-12 w-full animate-pulse bg-muted rounded-none' />
            ))}
          </div>
        ) : isEmpty ? (
          <div className='flex flex-col items-center justify-center py-12 text-center'>
            <p className='text-xs font-medium text-muted-foreground mb-4 tracking-wider'>
              No reminders yet
            </p>
            <Link
              to='/reminders'
              className='text-[10px] font-bold tracking-widest px-6 py-2 rounded-sm border border-primary/70 text-primary no-underline hover:bg-primary hover:text-primary-foreground transition-all'>
              Create
            </Link>
          </div>
        ) : (
          <div className='space-y-8'>
            <ReminderSection
              label='Upcoming'
              reminders={upcomingReminders}
              limit={UPCOMING_LIMIT}
              emptyHint={
                <Link
                  to='/reminders'
                  className='text-[10px] font-bold tracking-widest text-primary no-underline hover:text-primary/80 transition-colors'>
                  Set one
                </Link>
              }
            />
            {historyReminders.length > 0 && (
              <ReminderSection label='Recent' reminders={historyReminders} limit={RECENT_LIMIT} />
            )}
          </div>
        )}
      </div>
    </div>
  )
}

function ReminderSection({
  label,
  reminders,
  limit,
  emptyHint
}: {
  label: string
  reminders: MusicReminder[]
  limit: number
  emptyHint?: React.ReactNode
}) {
  const visible = reminders.slice(0, limit)
  const remaining = reminders.length - visible.length

  return (
    <div className='space-y-3'>
      <p className='text-[10px] font-bold tracking-widest text-muted-foreground'>{label}</p>
      {reminders.length === 0 ? (
        <div className='flex items-center gap-2 text-xs text-muted-foreground'>
          <span className='font-medium'>None</span>
          {emptyHint}
        </div>
      ) : (
        <div className='space-y-2'>
          {visible.map((reminder) => (
            <ReminderItem key={reminder.id} reminder={reminder} />
          ))}
          {remaining > 0 && (
            <p className='text-[10px] font-bold tracking-widest text-muted-foreground pt-1'>
              + {remaining} more
            </p>
          )}
        </div>
      )}
    </div>
  )
}

function ReminderItem({ reminder }: { reminder: MusicReminder }) {
  return (
    <div className='flex items-center gap-4 p-2 rounded-sm hover:bg-muted/40 transition-colors group'>
      <div className='relative shrink-0'>
        {reminder.albumCoverUrl ? (
          <img
            src={reminder.albumCoverUrl}
            alt={reminder.musicTitle}
            className='w-12 h-12 rounded-sm object-cover border border-border/50'
          />
        ) : (
          <div className='w-12 h-12 rounded-sm bg-muted flex items-center justify-center border border-border/50'>
            <Bell className='w-5 h-5 text-muted-foreground' />
          </div>
        )}
        {reminder.isSent && (
          <div className='absolute -top-1 -right-1 w-4 h-4 bg-background rounded-sm flex items-center justify-center border border-border/50'>
            <div className='w-2 h-2 bg-green-500 rounded-sm' />
          </div>
        )}
      </div>
      <div className='flex-1 min-w-0'>
        <p className='text-base font-bold tracking-tight truncate group-hover:text-primary transition-colors'>
          {reminder.musicTitle}
        </p>
        <p className='text-xs text-muted-foreground truncate font-medium'>{reminder.artistName}</p>
      </div>
      <span className='text-[9px] font-bold text-muted-foreground border border-border/50 px-2 py-1 rounded-sm'>
        {new Date(reminder.reminderDate).toLocaleDateString(undefined, {
          month: 'short',
          day: 'numeric'
        })}
      </span>
    </div>
  )
}

// apps/www/src/lib/components/dashboard/RemindersCard.svelte
<script lang="ts">
  import { GetMusicRemindersResponse } from '@gbfm/api/music-reminders'
  import { Bell, Plus } from 'lucide-svelte'

  type Reminder = typeof GetMusicRemindersResponse.Type.reminders[number]
  let { reminders, error = null }: { reminders: ReadonlyArray<Reminder>; error?: string | null } = $props()
  const upcoming = $derived(reminders.filter((item) => !item.isSent).toSorted((a, b) => Date.parse(a.reminderDate) - Date.parse(b.reminderDate)))
  const recent = $derived(reminders.filter((item) => item.isSent).toSorted((a, b) => Date.parse(b.reminderDate) - Date.parse(a.reminderDate)))
  const sections = $derived([
    { label: 'Upcoming', reminders: upcoming.slice(0, 5) },
    { label: 'Recent', reminders: recent.slice(0, 4) }
  ])

</script>

<section class="overflow-hidden rounded bg-card/15" aria-labelledby="reminders-heading">
  <header class="flex items-center justify-between bg-muted/20 p-5"><h2 id="reminders-heading" class="flex items-center gap-2 text-xs font-bold tracking-widest"><Bell class="size-3.5 text-primary" /> Reminders</h2><div class="flex gap-3 text-xs font-bold"><a class="flex items-center gap-1 no-underline" href="/reminders"><Plus class="size-3" /> New</a><a class="text-muted-foreground no-underline" href="/reminders">Manage</a></div></header>
  <div class="p-5">
    {#if error}<p class="text-sm text-destructive">{error}</p>
    {:else if reminders.length === 0}<div class="py-10 text-center"><p class="mb-4 text-sm text-muted-foreground">No reminders yet</p><a class="rounded border border-primary px-5 py-2 text-xs font-bold no-underline" href="/reminders">Create</a></div>
    {:else}
      {#each sections as section}
        {#if section.reminders.length}<div class="mb-7 space-y-2"><h3 class="text-xs font-bold tracking-widest text-muted-foreground">{section.label}</h3>{#each section.reminders as reminder}<a href={reminder.musicUrl} class="flex items-center gap-3 rounded p-2 no-underline hover:bg-muted/40"><span class="grid size-12 shrink-0 place-items-center overflow-hidden rounded border bg-muted">{#if reminder.albumCoverUrl}<img class="size-full object-cover" src={reminder.albumCoverUrl} alt="" />{:else}<Bell class="size-5" />{/if}</span><span class="min-w-0 flex-1"><strong class="block truncate">{reminder.musicTitle}</strong><small class="block truncate text-muted-foreground">{reminder.artistName}</small></span><time class="text-xs text-muted-foreground" datetime={reminder.reminderDate}>{new Date(reminder.reminderDate).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</time></a>{/each}</div>{/if}
      {/each}
    {/if}
  </div>
</section>
