// apps/www/src/lib/components/public/EpisodeRow.svelte
<script lang="ts">
  import { Pause, Play } from 'lucide-svelte'
  import { records, text, type PublicRecord } from '@/lib/public-content'

  let {
    episode,
    active,
    playing,
    onPlay,
  }: { episode: PublicRecord; active: boolean; playing: boolean; onPlay: () => void } = $props()

  const title = $derived(text(episode.title, 'Untitled episode'))

  const creators = $derived(records(episode.creators))

  const createdAt = $derived(text(episode.createdAt))

  const dateLabel = $derived(
    createdAt
      ? new Date(createdAt).toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        })
      : '',
  )
</script>

<article
  data-testid="episode-row"
  class={[
    'group/item flex max-w-2xl items-center gap-2 border-b border-border/40 px-1 py-1.5 text-base transition-colors last:border-b-0',
    active && 'text-highlight',
  ]}
>
  {#if text(episode.url)}
    <button
      type="button"
      aria-label={active && playing ? `Pause ${title}` : `Play ${title}`}
      onclick={onPlay}
      class={[
        'grid size-7 shrink-0 place-items-center rounded-sm transition-opacity hover:text-highlight',
        !active && 'opacity-40 group-hover/item:opacity-100 group-focus-within/item:opacity-100',
      ]}
    >
      {#if active && playing}<Pause size={16} strokeWidth={2} />{:else}<Play
          size={16}
          strokeWidth={2}
        />{/if}
    </button>
  {/if}
  <a
    href={`/mixes/${text(episode.slug, text(episode.id))}`}
    class={[
      'min-w-0 shrink truncate no-underline transition-colors group-hover/item:text-highlight',
      active ? 'text-highlight' : 'text-foreground',
    ]}>{title}</a
  >
  {#if dateLabel}<span class="shrink-0 text-[11px] tracking-widest text-muted-foreground"
      >{dateLabel}</span
    >{/if}
  {#if creators.length > 0}
    <span class="hidden min-w-0 truncate text-muted-foreground sm:inline">
      {#each creators as creator, index}
        {#if text(creator.username)}<a
            href={`/profile/${text(creator.username)}`}
            class="text-muted-foreground no-underline decoration-highlight/50 underline-offset-4 hover:underline"
            >{text(creator.name)}</a
          >{:else}<span>{text(creator.name)}</span>{/if}{#if index < creators.length - 1}<span
            class="mx-1 opacity-50">&</span
          >{/if}
      {/each}
    </span>
  {/if}
</article>

// apps/www/src/components/EpisodeRow.tsx
import { PlayToggle } from '@gbfm/ui'
import type { SelectAudio } from '@gbfm/vps/schemas'
import { Link } from '@tanstack/react-router'
import { cn } from '@/lib/utils'
import { useNowPlayingTrack, usePlayerActions, useTransport } from '@/services/player'
import { toPlaybackState } from '@/services/player/toPlaybackState'
import { toQueueTrack } from '@/services/player/toQueueTrack'

interface EpisodeRowProps {
  mix: SelectAudio
}

export function EpisodeRow({ mix }: EpisodeRowProps) {
  const current = useNowPlayingTrack()
  const { isPlaying, isBuffering, isLoaded } = useTransport()
  const { playTrack, togglePlayPause } = usePlayerActions()

  const isActive = current?.id === mix.id
  const hasCreators = Boolean(mix.creators && mix.creators.length > 0)
  const dateLabel = new Date(mix.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })

  const handlePlay = () => {
    if (isActive) togglePlayPause()
    else playTrack(toQueueTrack(mix))
  }

  return (
    <article
      data-testid='episode-row'
      className={cn(
        'group/item flex max-w-2xl items-center gap-2 px-1 py-1 text-sm transition-colors duration-150',
        isActive && 'text-highlight'
      )}>
      <PlayToggle
        state={toPlaybackState({ isCurrent: isActive, isPlaying, isBuffering, isLoaded })}
        variant='icon'
        label={mix.title}
        onToggle={handlePlay}
        className={cn(
          'shrink-0 transition-opacity',
          !isActive && 'opacity-40 group-hover/item:opacity-100 group-focus-within/item:opacity-100'
        )}
      />

      <Link
        to='/mixes/$mixId'
        params={{ mixId: mix.slug }}
        className={cn(
          'min-w-0 shrink truncate transition-colors group-hover/item:text-highlight',
          isActive ? 'text-highlight' : 'text-foreground'
        )}>
        {mix.title}
      </Link>

      <span className='shrink-0 text-[11px] tracking-widest text-muted-foreground'>
        {dateLabel}
      </span>

      {hasCreators && (
        <span className='hidden min-w-0 truncate text-muted-foreground sm:inline'>
          {mix.creators?.map((creator, index) => (
            <span key={creator.id}>
              {creator.username ? (
                <Link
                  to='/profile/$username'
                  params={{ username: creator.username }}
                  className='hover:underline decoration-highlight/50 underline-offset-4'>
                  {creator.name}
                </Link>
              ) : (
                <span>{creator.name}</span>
              )}
              {index < (mix.creators?.length || 0) - 1 && (
                <span className='mx-1 opacity-50'>&</span>
              )}
            </span>
          ))}
        </span>
      )}
    </article>
  )
}
