// apps/www/src/lib/components/public/TweetAuthorRow.svelte
<script lang="ts">
  import { text, type PublicRecord } from '@/lib/public-content'

  let {
    creator,
    createdAt,
    interactive = true,
  }: { creator: PublicRecord | null; createdAt: string; interactive?: boolean } = $props()

  const username = $derived(text(creator?.username))

  const name = $derived(text(creator?.name, 'goosebumps.fm'))

  const href = $derived(interactive && username ? `/profile/${username}` : undefined)

  const image = $derived(
    text(creator?.image, 'https://d20tmfka7s58bt.cloudfront.net/gb-default.png'),
  )

  const date = $derived(
    createdAt
      ? new Date(createdAt).toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        })
      : '',
  )
</script>

<div class="flex min-w-0 items-center gap-3">
  <a
    {href}
    aria-label={href ? `${name}'s profile` : undefined}
    class="shrink-0 overflow-hidden rounded-sm ring-1 ring-border/60 transition-transform hover:scale-[1.02]"
  >
    <img src={image} alt={`${name}'s avatar`} class="size-10 object-cover" loading="lazy" />
  </a>
  <div class="min-w-0 leading-tight">
    <a {href} class="block truncate font-bold text-foreground hover:underline">{name}</a>
    <div class="flex items-center gap-1.5 truncate text-base text-muted-foreground">
      {#if username}<a {href} class="truncate hover:text-foreground hover:underline">@{username}</a
        >{/if}
      {#if username && date}<span aria-hidden="true" class="text-muted-foreground/50">·</span>{/if}
      {#if date}<time
          class="shrink-0 font-mono text-xs text-muted-foreground/70"
          datetime={createdAt}>{date}</time
        >{/if}
    </div>
  </div>
</div>

// apps/www/src/components/TweetAuthorRow.tsx
import type { SelectMdxCompiledMicroPost } from '@gbfm/server/schemas'
import { Link } from '@/lib/navigation'
import { DEFAULT_IMAGE_URL } from '@/lib/constants'
import { usePublicProfile } from '@/lib/http'

type Props = {
  creators: NonNullable<SelectMdxCompiledMicroPost['creators']>
  createdAt?: string | Date | null
  interactive?: boolean
}

export function TweetAuthorRow({ creators, createdAt, interactive = true }: Props) {
  const primaryCreator = creators[0]
  const username = primaryCreator?.username ?? null
  const { data: profile } = usePublicProfile(username || '')
  const avatarUrl = profile?.image || DEFAULT_IMAGE_URL

  if (!primaryCreator) {
    return null
  }

  const formattedDate = createdAt
    ? new Date(createdAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
    : null

  const avatarImg = (
    <img
      src={avatarUrl}
      alt={`${primaryCreator.name}'s avatar`}
      className='h-10 w-10 object-cover'
      loading='lazy'
    />
  )

  const linkable = interactive && username

  return (
    <div className='flex min-w-0 items-center gap-3'>
      {linkable ? (
        <Link
          to='/profile/$username'
          params={{ username }}
          className='shrink-0 overflow-hidden rounded-sm ring-1 ring-border/60 transition-transform hover:scale-[1.02]'>
          {avatarImg}
        </Link>
      ) : (
        <div className='shrink-0 overflow-hidden rounded-sm ring-1 ring-border/60'>{avatarImg}</div>
      )}

      <div className='min-w-0 leading-tight'>
        {linkable ? (
          <Link
            to='/profile/$username'
            params={{ username }}
            className='block truncate font-bold text-foreground hover:underline'>
            {primaryCreator.name}
          </Link>
        ) : (
          <span className='block truncate font-bold text-foreground'>{primaryCreator.name}</span>
        )}
        <div className='flex items-center gap-1.5 truncate text-base text-muted-foreground'>
          {username ? (
            linkable ? (
              <Link
                to='/profile/$username'
                params={{ username }}
                className='truncate hover:text-foreground hover:underline'>
                @{username}
              </Link>
            ) : (
              <span className='truncate'>@{username}</span>
            )
          ) : null}
          {username && formattedDate ? (
            <span aria-hidden className='text-muted-foreground/50'>
              ·
            </span>
          ) : null}
          {formattedDate ? (
            <span className='shrink-0 font-mono text-xs text-muted-foreground/70'>
              {formattedDate}
            </span>
          ) : null}
        </div>
      </div>
    </div>
  )
}
