// apps/www/src/lib/components/public/TweetNav.svelte
<script lang="ts">
  import {
    NavigationResultResponse as NavigationResultSchema,
    type NavigationResultResponse
  } from '@gbfm/api/navigation'
  import { goto, preloadData } from '$app/navigation'
  import { ChevronLeft, ChevronRight } from 'lucide-svelte'
  import { Option, Schema } from 'effect'
  import { onMount } from 'svelte'

  type Command =
    | { _tag: 'Step'; direction: 'Back' | 'Forward' }
    | { _tag: 'Jump' }
    | { _tag: 'Open'; slug: string }

  let { slug, initialResult = null }: { slug: string; initialResult?: NavigationResultResponse | null } = $props()
  let result = $derived(initialResult)
  let busy = $state(false)
  let showStatus = $state(false)
  let message = $state('')
  let holdTimer: ReturnType<typeof setTimeout> | undefined
  let statusTimer: ReturnType<typeof setTimeout> | undefined
  let held = false
  let intent = 0

  const canBack = $derived(result?.capabilities.canStepBack ?? true)
  const canForward = $derived(result?.capabilities.canStepForward ?? true)
  const hasUnread = $derived(result?.capabilities.hasUnread ?? false)

  async function request(path: 'peek' | 'visit', command: Command) {
    const response = await fetch(`/api/content/posts/micro/navigate/${path}`, {
      method: 'POST',
      credentials: 'include',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        command,
        from: slug,
        intentToken: path === 'visit' ? crypto.randomUUID() : undefined
      })
    })
    if (!response.ok) throw new Error('Navigation unavailable')
    return path === 'visit'
      ? null
      : Option.getOrNull(Schema.decodeUnknownOption(NavigationResultSchema)(await response.json()))
  }

  function accept(next: NavigationResultResponse | null) {
    if (!next) return
    result = next
    const targets = next.neighbourhood
      ? [...next.neighbourhood.back.slice(0, 3), ...next.neighbourhood.forward.slice(0, 3)]
      : [next.neighbours.back, next.neighbours.forward]
    for (const target of new Set(targets)) {
      if (target === undefined) continue
      void preloadData(`/tweet/${encodeURIComponent(String(target))}`)
    }
  }

  async function navigate(command: Extract<Command, { _tag: 'Step' | 'Jump' }>) {
    if (busy) return
    const currentIntent = ++intent
    const expected =
      command._tag === 'Step'
        ? command.direction === 'Back'
          ? result?.neighbours.back
          : result?.neighbours.forward
        : undefined
    busy = true
    message = ''
    statusTimer = setTimeout(() => {
      if (intent === currentIntent) showStatus = true
    }, 400)

    void request('visit', command).catch(() => undefined)

    try {
      const peek = request('peek', command)
      if (expected) await Promise.all([goto(`/tweet/${encodeURIComponent(expected)}`), peek])
      else {
        const next = await peek
        if (!next) throw new Error('Invalid navigation response')
        await goto(`/tweet/${encodeURIComponent(next.destination.slug)}`)
      }
    } catch {
      if (intent === currentIntent) message = 'Could not load another tweet.'
    } finally {
      if (intent === currentIntent) {
        if (statusTimer) clearTimeout(statusTimer)
        showStatus = false
        busy = false
      }
    }
  }

  function startHold() {
    held = false
    holdTimer = setTimeout(() => {
      held = true
      void navigate({ _tag: 'Jump' })
    }, 900)
  }

  function cancelHold(runTap: boolean) {
    if (holdTimer) clearTimeout(holdTimer)
    holdTimer = undefined
    if (runTap && !held) void navigate({ _tag: 'Step', direction: 'Forward' })
  }

  $effect(() => {
    const currentSlug = slug
    const serverResult = initialResult
    if (serverResult) accept(serverResult)
    else {
      result = null
      void request('peek', { _tag: 'Open', slug: currentSlug }).then(accept).catch(() => undefined)
    }
    void request('visit', { _tag: 'Open', slug: currentSlug }).catch(() => undefined)
  })

  onMount(() => {
    const keydown = (event: KeyboardEvent) => {
      if (event.metaKey || event.ctrlKey || event.altKey || event.shiftKey || event.repeat) return
      const target = event.target
      if (
        target instanceof HTMLInputElement ||
        target instanceof HTMLTextAreaElement ||
        target instanceof HTMLSelectElement ||
        (target instanceof HTMLElement && target.isContentEditable)
      )
        return
      if (event.key === 'ArrowLeft' && canBack) {
        event.preventDefault()
        void navigate({ _tag: 'Step', direction: 'Back' })
      }
      if (event.key === 'ArrowRight' && canForward) {
        event.preventDefault()
        void navigate({ _tag: 'Step', direction: 'Forward' })
      }
    }
    window.addEventListener('keydown', keydown)
    return () => {
      window.removeEventListener('keydown', keydown)
      if (holdTimer) clearTimeout(holdTimer)
      if (statusTimer) clearTimeout(statusTimer)
    }
  })
</script>

<nav aria-label="Tweet navigation" aria-busy={busy}>
  <div class="flex items-center gap-1 lg:hidden">
    <button type="button" aria-label="Previous tweet" disabled={!canBack || busy} class="inline-flex size-8 items-center justify-center text-muted-foreground transition-colors hover:bg-muted/60 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-25" onclick={() => void navigate({ _tag: 'Step', direction: 'Back' })}><ChevronLeft size={16} /></button>
    <button type="button" aria-label={hasUnread ? 'Next tweet (hold for random)' : 'Next tweet'} disabled={!canForward || busy} class="inline-flex size-8 touch-none items-center justify-center text-muted-foreground transition-colors hover:bg-muted/60 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-25" onpointerdown={startHold} onpointerup={() => cancelHold(true)} onpointerleave={() => cancelHold(false)} onpointercancel={() => cancelHold(false)} onclick={(event) => { if (event.detail === 0) void navigate({ _tag: 'Step', direction: 'Forward' }) }}><ChevronRight size={16} /></button>
  </div>

  <button type="button" aria-label="Previous tweet" disabled={!canBack || busy} class="fixed left-[max(1rem,calc(50%-30rem))] top-1/2 z-30 hidden size-11 -translate-y-1/2 items-center justify-center text-muted-foreground transition-colors hover:bg-muted/60 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-20 lg:flex" onclick={() => void navigate({ _tag: 'Step', direction: 'Back' })}><ChevronLeft size={24} /></button>
  <button type="button" aria-label={hasUnread ? 'Next tweet (hold for random)' : 'Next tweet'} disabled={!canForward || busy} class="fixed right-[max(1rem,calc(50%-30rem))] top-1/2 z-30 hidden size-11 -translate-y-1/2 touch-none items-center justify-center text-muted-foreground transition-colors hover:bg-muted/60 hover:text-foreground disabled:cursor-not-allowed disabled:opacity-20 lg:flex" onpointerdown={startHold} onpointerup={() => cancelHold(true)} onpointerleave={() => cancelHold(false)} onpointercancel={() => cancelHold(false)} onclick={(event) => { if (event.detail === 0) void navigate({ _tag: 'Step', direction: 'Forward' }) }}><ChevronRight size={24} /></button>

  <div class="pointer-events-none fixed inset-x-0 top-4 z-50 flex justify-center">
    {#if showStatus}<span role="status" class="bg-card px-3 py-1 text-xs text-muted-foreground shadow-sm">Loading tweet…</span>{:else if message}<span role="alert" class="bg-card px-3 py-1 text-xs text-destructive shadow-sm">{message}</span>{/if}
  </div>
</nav>

// apps/www/src/components/TweetNav.tsx
import { useAtomSet, useAtomValue } from '@effect/atom-react'
import type { NavigationResultResponse } from '@gbfm/api/navigation'
import { useHotkey } from '@tanstack/react-hotkeys'
import { useRouter } from '@tanstack/react-router'
import { Effect } from 'effect'
import * as Atom from 'effect/unstable/reactivity/Atom'
import { ChevronLeft, ChevronRight, LoaderCircle } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { HoldToRandomButton } from '@/components/HoldToRandomButton'
import { jump, stepBack, stepForward } from '@/lib/navigation-commands'
import { useNavigateMicroPosts } from '@/lib/http'
import { runNavigationIntent } from '@/lib/navigation-intent'
import { cn } from '@/lib/utils'

type Props = {
  slug: string
  initialCapabilities: Capabilities
}

type Capabilities = NavigationResultResponse['capabilities']

const iconButtonClassName =
  'inline-flex h-8 w-8 cursor-pointer items-center justify-center rounded-sm text-muted-foreground transition-colors hover:bg-muted/60 hover:text-foreground'
const disabledIconButtonClassName =
  'inline-flex h-8 w-8 cursor-not-allowed items-center justify-center rounded-sm text-muted-foreground/25'

const flankBaseClassName =
  'fixed top-1/2 z-30 hidden h-11 w-11 -translate-y-1/2 items-center justify-center rounded-sm text-muted-foreground transition-colors lg:flex'
const flankClassName = cn(
  flankBaseClassName,
  'cursor-pointer hover:bg-muted/60 hover:text-foreground'
)
const disabledFlankClassName = cn(flankBaseClassName, 'cursor-not-allowed text-muted-foreground/20')

function PrevLink({ enabled, onTap }: { enabled: boolean; onTap: () => void }) {
  if (!enabled) {
    return (
      <span aria-hidden className={disabledIconButtonClassName}>
        <ChevronLeft className='h-4 w-4' />
      </span>
    )
  }

  return (
    <button
      type='button'
      aria-label='Previous tweet'
      onClick={onTap}
      className={iconButtonClassName}>
      <ChevronLeft className='h-4 w-4' />
    </button>
  )
}

function NextLink({
  enabled,
  hasUnread,
  onTap,
  onHoldComplete
}: {
  enabled: boolean
  hasUnread: boolean
  onTap: () => void
  onHoldComplete: () => void
}) {
  if (!enabled) {
    return (
      <span aria-hidden className={disabledIconButtonClassName}>
        <ChevronRight className='h-4 w-4' />
      </span>
    )
  }

  return (
    <HoldToRandomButton
      onTap={onTap}
      onHoldComplete={hasUnread ? onHoldComplete : () => {}}
      ariaLabel='Next tweet (hold for random)'
      className={iconButtonClassName}>
      <ChevronRight className='h-4 w-4' />
    </HoldToRandomButton>
  )
}

function FlankingArrows({
  canStepBack,
  canStepForward,
  hasUnread,
  onTapPrev,
  onTapNext,
  onHoldComplete
}: {
  canStepBack: boolean
  canStepForward: boolean
  hasUnread: boolean
  onTapPrev: () => void
  onTapNext: () => void
  onHoldComplete: () => void
}) {
  const leftPosition = 'left-[max(1rem,calc(50%-30rem))]'
  const rightPosition = 'right-[max(1rem,calc(50%-30rem))]'

  return (
    <>
      {canStepBack ? (
        <button
          type='button'
          aria-label='Previous tweet'
          onClick={onTapPrev}
          className={cn(flankClassName, leftPosition)}>
          <ChevronLeft className='h-6 w-6' />
        </button>
      ) : (
        <span aria-hidden className={cn(disabledFlankClassName, leftPosition)}>
          <ChevronLeft className='h-6 w-6' />
        </span>
      )}

      {canStepForward ? (
        <HoldToRandomButton
          onTap={onTapNext}
          onHoldComplete={hasUnread ? onHoldComplete : () => {}}
          ariaLabel='Next tweet (hold for random)'
          className={cn(flankClassName, rightPosition)}>
          <ChevronRight className='h-6 w-6' />
        </HoldToRandomButton>
      ) : (
        <span aria-hidden className={cn(disabledFlankClassName, rightPosition)}>
          <ChevronRight className='h-6 w-6' />
        </span>
      )}
    </>
  )
}

export function TweetNav({ slug, initialCapabilities }: Props) {
  const router = useRouter()
  const { navigateMicroPostsEffect } = useNavigateMicroPosts()
  const capabilitiesAtom = useMemo(
    () => Atom.make<Capabilities>(initialCapabilities),
    [initialCapabilities]
  )
  const capabilities = useAtomValue(capabilitiesAtom)
  const setCapabilities = useAtomSet(capabilitiesAtom)
  const pendingRef = useRef(false)
  const [isNavigating, setIsNavigating] = useState(false)

  useEffect(() => {
    setCapabilities(initialCapabilities)
  }, [initialCapabilities, setCapabilities])

  const navigate = (
    command: (intentToken: string) => Effect.Effect<NavigationResultResponse, unknown>
  ) => {
    if (pendingRef.current) return

    pendingRef.current = true
    setIsNavigating(true)
    runNavigationIntent(
      command(crypto.randomUUID()).pipe(
        Effect.tap((result) => Effect.sync(() => setCapabilities(result.capabilities))),
        Effect.flatMap((result) =>
          Effect.promise(() =>
            router.navigate({ to: '/tweet/$slug', params: { slug: result.destination.slug } })
          )
        ),
        Effect.asVoid,
        Effect.ensuring(
          Effect.sync(() => {
            pendingRef.current = false
            setIsNavigating(false)
          })
        )
      )
    )
  }

  const goToPrev = () =>
    navigate((intentToken) => stepBack(navigateMicroPostsEffect, { from: slug, intentToken }))
  const goToNext = () =>
    navigate((intentToken) => stepForward(navigateMicroPostsEffect, { from: slug, intentToken }))
  const onHoldComplete = () =>
    navigate((intentToken) => jump(navigateMicroPostsEffect, { from: slug, intentToken }))

  useHotkey('ArrowLeft', goToPrev)
  useHotkey('ArrowRight', goToNext)

  const { canStepBack, canStepForward, hasUnread } = capabilities

  return (
    <div aria-busy={isNavigating}>
      <div className='flex items-center gap-1 lg:hidden'>
        <PrevLink enabled={canStepBack && !isNavigating} onTap={goToPrev} />
        <NextLink
          enabled={canStepForward && !isNavigating}
          hasUnread={hasUnread}
          onTap={goToNext}
          onHoldComplete={onHoldComplete}
        />
      </div>
      {isNavigating && (
        <div
          role='status'
          aria-live='polite'
          className='mt-2 flex items-center gap-2 font-mono text-xs text-muted-foreground'>
          <LoaderCircle aria-hidden className='h-3.5 w-3.5 animate-spin' />
          Loading tweet…
        </div>
      )}
      <FlankingArrows
        canStepBack={canStepBack && !isNavigating}
        canStepForward={canStepForward && !isNavigating}
        hasUnread={hasUnread}
        onTapPrev={goToPrev}
        onTapNext={goToNext}
        onHoldComplete={onHoldComplete}
      />
    </div>
  )
}
